# Generated by Django 3.0.9 on 2020-09-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waittime',
            name='total_time_hours',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='waittime',
            name='total_time_mins',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
