# Generated by Django 3.0.9 on 2020-09-19 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20200919_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='address',
            name='object_id',
        ),
        migrations.AddField(
            model_name='pollinglocation',
            name='address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest_api.Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest_api.Address'),
            preserve_default=False,
        ),
    ]
