# Generated by Django 3.0.9 on 2020-09-20 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_auto_20200920_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='polling_location',
            new_name='polling_locations',
        ),
    ]
