# Generated by Django 3.0.9 on 2020-10-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_auto_20200920_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollinglocation',
            name='end_date',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='pollinglocation',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pollinglocation',
            name='polling_hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pollinglocation',
            name='start_date',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='pollinglocation',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
